name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Generate Solution
      run: chmod +x setup_sln.sh && ./setup_sln.sh
    - name: Restore dependencies
      run: dotnet restore MOT.sln
    - name: Build
      run: dotnet build MOT.sln --no-restore
    - name: Test
      run: dotnet test MOT.sln --no-build --verbosity normal
