name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore MOT.Api/MOT.Api.csproj
      
    - name: Build
      run: dotnet build MOT.Api/MOT.Api.csproj --no-restore
      
    - name: Test
      run: dotnet test MOT.Tests/MOT.Tests.csproj --no-build --verbosity normal
